"""Tests for .codeatlas-ignore pattern matching."""

from pathlib import Path

from codeatlas.ignore import IgnoreMatcher, load_ignore_file


def test_empty_patterns() -> None:
    m = IgnoreMatcher([])
    assert not m.is_ignored("src/main.py")


def test_simple_filename_pattern() -> None:
    m = IgnoreMatcher(["secrets.env"])
    assert m.is_ignored("secrets.env")
    assert m.is_ignored("config/secrets.env")
    assert not m.is_ignored("secrets.env.example")


def test_wildcard_pattern() -> None:
    m = IgnoreMatcher(["*.log"])
    assert m.is_ignored("app.log")
    assert m.is_ignored("logs/build.log")
    assert not m.is_ignored("app.txt")


def test_directory_pattern() -> None:
    m = IgnoreMatcher(["build/"])
    assert m.is_ignored("build", is_dir=True)
    assert not m.is_ignored("build", is_dir=False)


def test_nested_path_pattern() -> None:
    m = IgnoreMatcher(["src/generated/*"])
    assert m.is_ignored("src/generated/api.py")
    assert not m.is_ignored("src/main.py")


def test_comment_and_blank_lines() -> None:
    m = IgnoreMatcher(["# this is a comment", "", "*.tmp", "   "])
    assert m.is_ignored("build.tmp")
    # Comments don't match
    assert not m.is_ignored("# this is a comment")


def test_negation_pattern() -> None:
    m = IgnoreMatcher(["*.log", "!important.log"])
    assert m.is_ignored("debug.log")
    assert not m.is_ignored("important.log")


def test_double_star_pattern() -> None:
    m = IgnoreMatcher(["**/node_modules/*"])
    assert m.is_ignored("app/node_modules/react")
    assert m.is_ignored("deep/path/node_modules/lib")


def test_load_nonexistent_file(tmp_path: Path) -> None:
    matcher = load_ignore_file(tmp_path)
    assert not matcher.is_ignored("anything.py")


def test_load_existing_file(tmp_path: Path) -> None:
    (tmp_path / ".codeatlas-ignore").write_text("*.bak\nbuild/\n# comment\n")
    matcher = load_ignore_file(tmp_path)
    assert matcher.is_ignored("config.bak")
    assert matcher.is_ignored("src/old.bak")
    assert matcher.is_ignored("build", is_dir=True)
    assert not matcher.is_ignored("src/main.py")


def test_load_file_with_encoding_error(tmp_path: Path) -> None:
    # Write invalid UTF-8 bytes
    (tmp_path / ".codeatlas-ignore").write_bytes(b"\xff\xfe\x00invalid")
    matcher = load_ignore_file(tmp_path)
    # Should still work, returning an empty matcher or one with the attempted patterns
    # The important thing is it doesn't crash
    assert isinstance(matcher, IgnoreMatcher)


def test_backslash_paths_normalized() -> None:
    m = IgnoreMatcher(["src/main.py"])
    # Windows-style path separator
    assert m.is_ignored("src\\main.py")


def test_no_match_returns_false() -> None:
    m = IgnoreMatcher(["*.log", "build/"])
    assert not m.is_ignored("src/main.py")


def test_negation_without_positive_match() -> None:
    """A negation pattern alone has no effect."""
    m = IgnoreMatcher(["!keepme.py"])
    assert not m.is_ignored("keepme.py")
    assert not m.is_ignored("anything.py")


def test_suffix_path_match() -> None:
    """A pattern with a slash matches any suffix of the path."""
    m = IgnoreMatcher(["dist/bundle.js"])
    assert m.is_ignored("dist/bundle.js")
    assert m.is_ignored("app/dist/bundle.js")


def test_indexer_respects_codeatlas_ignore(tmp_path: Path) -> None:
    """End-to-end: indexer's _discover_files honors the ignore file."""
    from codeatlas.config import CodeAtlasConfig
    from codeatlas.graph.store import GraphStore
    from codeatlas.indexer import RepoIndexer

    # Build a small repo with a file that should be ignored
    (tmp_path / "app.py").write_text("def main(): pass\n")
    (tmp_path / "generated.py").write_text("# autogenerated\n")
    (tmp_path / ".codeatlas-ignore").write_text("generated.py\n")

    config = CodeAtlasConfig(repo_root=tmp_path)
    store = GraphStore(":memory:")
    indexer = RepoIndexer(config, store)
    files = indexer._discover_files()
    names = {f.name for f in files}
    assert "app.py" in names
    assert "generated.py" not in names
