"""Generate a human- and agent-readable architecture overview from the graph.

"Explain this repo" — one call assembles the structural story (scale, most
central symbols, module communities, public API surface) into Markdown, reusing
the existing analysis methods on GraphStore.
"""

from __future__ import annotations

from typing import Any

from codeatlas.graph.store import GraphStore


def build_repo_explainer(
    store: GraphStore, *, repo_name: str = "this repository"
) -> dict[str, Any]:
    """Return ``{repo, markdown, sections}`` describing the codebase's architecture."""
    stats = store.get_stats()
    languages = store.get_language_breakdown()
    top_symbols = store.get_pagerank_ranking(limit=10)
    communities = store.get_community_summary(min_size=3)[:5]
    api_surface = [
        {
            "name": sym.name,
            "qualified_name": sym.qualified_name,
            "kind": sym.kind.value,
            "file": sym.file_path,
        }
        for sym in store.get_api_surface(limit=15)
    ]
    sections = {
        "stats": stats,
        "languages": languages,
        "top_symbols": top_symbols,
        "communities": communities,
        "api_surface": api_surface,
    }
    return {
        "repo": repo_name,
        "markdown": _render_markdown(repo_name, sections),
        "sections": sections,
    }


def _render_markdown(repo_name: str, sections: dict[str, Any]) -> str:
    stats = sections["stats"]
    languages = sections["languages"]
    top_langs = sorted(languages.items(), key=lambda kv: -kv[1])[:5]
    lines: list[str] = [
        f"# Architecture overview — {repo_name}",
        "",
        "## At a glance",
        "",
        f"- **Files:** {stats.get('files', 0):,}",
        f"- **Symbols:** {stats.get('symbols', 0):,}",
        f"- **Relationships:** {stats.get('relationships', 0):,}",
    ]
    if top_langs:
        langs = ", ".join(f"{lang} ({count})" for lang, count in top_langs)
        lines.append(f"- **Top languages:** {langs}")

    lines += ["", "## Most central symbols (PageRank)", ""]
    for sym in sections["top_symbols"]:
        lines.append(
            f"- `{sym['qualified_name']}` ({sym['kind']}) — {sym['file']}"
            f" · score {float(sym['score']):.4f}"
        )

    communities = sections["communities"]
    if communities:
        lines += ["", "## Modules / communities", ""]
        for i, comm in enumerate(communities, 1):
            sample = ", ".join(f"`{m['name']}`" for m in comm.get("sample", [])[:4])
            lines.append(f"- **Cluster {i}** — {comm['size']} symbols: {sample}")

    api = sections["api_surface"]
    if api:
        lines += ["", "## Public API surface", ""]
        for sym in api:
            lines.append(f"- `{sym['qualified_name']}` ({sym['kind']}) — {sym['file']}")

    lines += [
        "",
        "_Generated by CodeAtlas — paste into your agent to orient it instantly._",
    ]
    return "\n".join(lines)
